### ISSUE TITLE
[Linux 64] Cannot open a file

### ISSUE THREAD

**Issue by rchastain** [wp-xyz/Hex#1]
Hello!

I am trying to use the Hex editor on Linux 64. I cannot open a file. When I try to open a file, after I select the file name, I get a little empty window (upon the main window) that I cannot close.

I tried with two different versions of Lazarus (2.0.8 and 2.0.10). I downloaded the OMultiPanel component [here](https://sourceforge.net/p/omultipanel/code/HEAD/tree/).

Regards.

Roland

![screenshot](https://user-images.githubusercontent.com/13957204/112850874-b62a5600-90aa-11eb-9c9d-d19a98fc3740.png)

**Comment by wp-xyz** [comment]
Please test.

**Comment by rchastain** [comment]
> Please test.

It works now. Thank you.

By the way, why do you provide another _OMultiPanel.pas?_ Shall we replace the original file from the package?

**Comment by rchastain** [comment]
I would like to announce your project on this [website](https://www.developpez.net/forums/f21/autres-langages/pascal/). Could you please tell me what needs to be said about the project, according to you? What would you think of creating a little _README?_ When you have time, of course.

**Comment by wp-xyz** [comment]
> By the way, why do you provide another _OMultiPanel.pas?_ Shall we replace the original file from the package?

Ah, this is a left-over from a previous version where I had tried to create all the subpanels at runtime (which would not force me to install this package which I don't use for anything else) - but I did not get it to work and finally switched to designtime-creation of the MultiPanel. I'll do some more tests and then delete the unit here.

**Comment by wp-xyz** [comment]
> I would like to announce your project on this [website](https://www.developpez.net/forums/f21/autres-langages/pascal/). Could you please tell me what needs to be said about the project, according to you? What would you think of creating a little _README?_ When you have time, of course.

Nice. But let me first write the README in the next days.

**Comment by rchastain** [comment]
> Nice. But let me first write the README in the next days.

OK. Thanks.

**Comment by rchastain** [comment]
> Nice. But let me first write the README in the next days.

Thank you for the README. After reading it I could better understand the (very powerful) features of the application. Congratulations for that beautiful software!

[Announcement](https://www.developpez.net/forums/d2106924/autres-langages/pascal/lazarus/telechargez/hex-editeur-hexadecimal/#post11706365) made.

Bis bald!

**Comment by wp-xyz** [comment]
> > By the way, why do you provide another _OMultiPanel.pas?_ Shall we replace the original file from the package?
> 
> Ah, this is a left-over from a previous version where I had tried to create all the subpanels at runtime (which would not force me to install this package which I don't use for anything else) - but I did not get it to work and finally switched to designtime-creation of the MultiPanel. I'll do some more tests and then delete the unit here.

Now I looked at it again and was able to create the OMultiPanel at runtime. Therefore, it is no longer required to install this package into Lazarus since its only unit is contained in the source folder.

**Comment by rchastain** [comment]
Found a last small issue. On Linux, I can't open a file which hasn't an extension in its name, because of the value of the filter (`*.*`).

The simplest solution (if I may suggest) would be to remove these lines, which (I believe) are not needed:

```
procedure TMainForm.acFileOpenExecute(Sender: TObject);
var
  i : integer;
begin
  with OpenDialog do begin
    FileName := '*.*'; // <----
    Filter := 'All files (*.*)|*.*'; // <----
    DefaultExt := ''; // <----
```

**Comment by wp-xyz** [comment]
Changed the filter mask to contain also the '*'. Should work always now.
