### ISSUE TITLE
[Discussion] Release notes being automated

### ISSUE THREAD

**Issue by gcarreno** [wp-xyz/Hex#9]
Hey WP(@wp-xyz),

There are 2 was to fill in the release notes for the automated release that is created.
1. A file on the repo that you update and is read when the automated release happens
2. A tool that will pickup all the commit messages and do it for you

I've implemented both in the past.
I tend to suggest 1. to the ones that like to be in control of it all.
I, myself, use 2. and the tool of my choice is [git-cliff](https://github.com/orhun/git-cliff). It also has a companion action that can be used to coordinate it all in the GitHub context.

The way 1. works is simple: You create a file, lets say `release_notes.md`, that you always keep updated every time you do a commit. And then you completely reset when you've pushed the tag.

For option 2., it's a bit more _involved_. Not complicated. The only thing you have to do is to follow the standards of commit messages that is suggested here:
- https://git-cliff.org/docs/configuration/git/#conventional_commits
- https://www.conventionalcommits.org/en/v1.0.0

If you do that, then the companion action will do the work for you. And you can run the `git-cliff` command locally to have a `CHANGELOG.md` file created and updated, on your repo that will list all the changes made.

Please tell me what route you wanna go, since this is the last step for the full completion of the automation of the `CI`/`CD`.

Cheers,
Gus

**Comment by wp-xyz** [comment]
Just added a `release_notes.md` for option 1.

**Comment by gcarreno** [comment]
Hey WP(@wp-xyz),

Great!!
Expect a new `PR` in the near future to account for that!!
And thanks !!

Cheers,
Gus

**Comment by gcarreno** [comment]
All done, closing!!
